### ISSUE TITLE
Undefined index: REMOTE_ADDR by executing Kirby-Queue worker

### ISSUE THREAD

**Issue by wottpal** [jenstornell/kirby-autologin#4]
Hey Jens,
new day new issue 😛

Your plugin is now working just fine for me! But when I execute the worker of the [Queue for Kirby](https://github.com/sebsel/queue-for-kirby) Plugin in the Terminal (which actually has nothing to do with your plugin) I get the following output:

```
PHP Notice:  Undefined index: REMOTE_ADDR in /var/www/wottpal.com/site/plugins/kirby-autologin/kirby-autologin.php on line 95
```

Which sounds totally reasonable to me because there is no `REMOTE_ADDR` when I execute some PHP in the terminal, right? So maybe you should include an if-statement if a  `REMOTE_ADDR` (or `REMOTE_NAME`) is given.

What do you think?

Dennis

**Comment by jenstornell** [comment]
Does it work if you change it to REMOTE_NAME?

**Comment by wottpal** [comment]
Hey Jens,
sorry for not getting your point. But I'm actually neither using `REMOTE_ADDR` nor `REMOTE_NAME` anywhere by myself. All I do is executing the `worker.php` (from [this](https://github.com/sebsel/queue-for-kirby) plugin) in the Terminal. This runs the following job:

```php
  queue::define('commit_and_push_comment', function($job) {

    // Manually re-configure `gcapc` because the cronjob doesn't know the actual server-address
    c::set([
      'gcapc-path' => kirby()->roots()->index(),
      'gcapc-branch' => 'master',
      'gcapc-pull' => true,
      'gcapc-push' => true,
      'gcapc-commit' => true
    ]);

    // Instantiate the `KirbyGitHelper`
    kirby()->plugin('git-commit-and-push-content');
    $gitHelper = new KirbyGitHelper();

    // Commit & Push the new comment asynchronously
    $uri = $job->get('uri');
    $commitMessage = "commented on " . $uri;
    $gitHelper->kirbyChange($commitMessage);

  });
```

Which should have nothing to do with auto login but I assume you must interfere sessions at some point to enable auto-login..

Dennis

PS: I'm attending at the Kirby workshop in Berlin today to make you a bit jealous 😛

**Comment by sebsel** [comment]
I would say: just use Kirby's `visitor::ip()` to get the IP. The problem here is not that there is no IP (because there just is no visitor at the command line), the problem is that you don't check it properly, which results in a Notice. :)

If you look at the source of `visitor::ip()`, you'll see that it does not use one of those internal Array's, so it won't give an key-not-exists-notice.

**Comment by jenstornell** [comment]
I've made a new release with the `visitor::ip()`. @wottpal, maybe you can try the new version and see if that did the trick?

**Comment by wottpal** [comment]
The error is gone and everything still works perfectly.
Thanks!
